version: '3'
services:
  ui:
    image: tianlechen/astroturf
    ports:
      - "5000:5000"
    volumes:
      - .:/astroturf
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=astroturf-ui.json
    entrypoint: gunicorn -w 2 -b 0.0.0.0:5000 ui:app
  infer:
    image: tianlechen/astroturf:gpu
    volumes: 
      - .:/astroturf
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=astroturf-ui.json
    entrypoint: uvicorn --host 0.0.0.0 --port 8000 --workers 1 infer:app
  scraper:
    image: tianlechen/astroturf
    volumes:
      - .:/astroturf
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=astroturf-update.json
    entrypoint: python scraper_listener.py --limit 1000
  trainer:
    image: tianlechen/astroturf:gpu
    volumes:
      - .:/astroturf
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=astroturf-update.json
    entrypoint: python trainer_listener.py --blocksize 128 --maxsteps 1000 --forceupdate True
