version: '3'
services:
  shell:
    build:
      context: .
    volumes:
      - .:/astroturf
    entrypoint: bash
  ui:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/astroturf
    entrypoint: gunicorn -w 2 -b 0.0.0.0:5000 ui:app
  refreshfinetune:
    build:
      context: .
    volumes:
      - .:/astroturf
    entrypoint: python refresh_user_finetuned.py
  refreshdata:
    build:
      context: .
    volumes:
      - .:/astroturf
    entrypoint: python refresh_user_comments.py
