version: '3'
services:

  listener:
    image: astroturf
    volumes:
      - .:/workdir
    entrypoint: python -u listener.py
    deploy:
      restart_policy:
        condition: on-failure

  scraper:
    image: astroturf
    volumes:
      - .:/workdir
    entrypoint: python -u scraper.py
    deploy:
      restart_policy:
        condition: on-failure

  trainer:
    image: astroturf
    volumes:
      - .:/workdir
    entrypoint: python -u trainer.py
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        reservations:
          devices:
          - capabilities: [gpu]

  responder:
    image: astroturf
    volumes:
      - .:/workdir
    entrypoint: python -u responder.py
    deploy:
      restart_policy:
        condition: on-failure

  ignorer:
    image: astroturf
    volumes:
      - .:/workdir
    entrypoint: python -u ignorer.py
    deploy:
      restart_policy:
        condition: on-failure
