version: '3'
services:
  ui:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/astroturf
    entrypoint: gunicorn -w 2 -b 0.0.0.0:5000 ui:app
  getcomments:
    build:
      context: .
    volumes:
      - .:/astroturf
    entrypoint: python get_comments.py