version: '3'
services:

  listener:
    image: astroturf
    volumes:
      - .:/workdir
    entrypoint: python -u listener.py

  scraper:
    image: astroturf
    volumes:
      - .:/workdir
    entrypoint: python -u scraper.py

  trainer:
    image: astroturf
    volumes:
      - .:/workdir
    entrypoint: python -u trainer.py

  responder:
    image: astroturf
    volumes:
      - .:/workdir
    entrypoint: python -u responder.py
