version: '3'
services:
  ui:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/astroturf
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=astroturf-ui.json
    entrypoint: gunicorn -w 1 -b 0.0.0.0:5000 ui:app
  infer:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    volumes: 
      - .:/astroturf
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=astroturf-ui.json
    entrypoint: uvicorn --host 0.0.0.0 --port 8000 --workers 1 infer:app
  scraper:
    build:
      context: .
    volumes:
      - .:/astroturf
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=astroturf-update.json
    entrypoint: python scraper_listener.py --limit 1000
  trainer:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    volumes:
      - .:/astroturf
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=astroturf-update.json
    entrypoint: python trainer_listener.py --blocksize 128 --maxsteps 1000 --forceupdate True
