version: '3'
services:
  ui:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/astroturf
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=astroturf-ui.json
    entrypoint: gunicorn -w 2 -b 0.0.0.0:5000 ui:app
  refreshlistener:
    build:
      context: .
    volumes:
      - .:/astroturf
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=astroturf-update.json
    entrypoint: python refresh_listener.py
