version: '3'
services:
  ui:
    image: astroturf
    ports:
      - "5000:5000"
    entrypoint: gunicorn -w 1 -b 0.0.0.0:5000 ui:app
  infer:
    image: astroturf
    entrypoint: uvicorn --host 0.0.0.0 --port 8000 --workers 1 infer_service:app
  update:
    image: astroturf
    volumes:
      - .:/astroturf
    entrypoint: uvicorn --host 0.0.0.0 --port 8000 --workers 1 update_service:app
  updateworker:
    image: astroturf
    entrypoint: python update_worker.py --limit 100 --blocksize 128 --maxsteps 1000 --forceupdate True
