version: '3'
services:
  ui:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/astroturf
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=astroturf-ui.json
    entrypoint: gunicorn -w 1 -b 0.0.0.0:5000 ui:app
  inferservice:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    volumes: 
      - .:/astroturf
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=astroturf-ui.json
    entrypoint: uvicorn --host 0.0.0.0 --port 8000 --workers 1 infer_service:app
  updateservice:
    build:
      context: .
    volumes:
      - .:/astroturf
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=astroturf-update.json
    entrypoint: uvicorn --host 0.0.0.0 --port 8000 --workers 1 update_service:app
